"""add_execution_tables

Revision ID: 30b18a0564e2
Revises: d89eca32582d
Create Date: 2026-01-30 14:44:57.907303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b18a0564e2'
down_revision: Union[str, None] = 'd89eca32582d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False, comment='Agent 名称'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='是否成功'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False, comment='执行耗时（毫秒）'),
    sa.Column('model_used', sa.String(length=100), nullable=True, comment='使用的模型'),
    sa.Column('iterations', sa.Integer(), nullable=False, comment='迭代次数'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_name'), 'agent_executions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_executions_created_at'), 'agent_executions', ['created_at'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=100), nullable=False, comment='Temporal Workflow ID'),
    sa.Column('workflow_type', sa.String(length=50), nullable=False, comment='工作流类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='执行状态'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='工作流标题'),
    sa.Column('input_data', sa.JSON(), nullable=True, comment='输入参数'),
    sa.Column('output_data', sa.JSON(), nullable=True, comment='输出结果'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=True)
    op.create_index(op.f('ix_workflow_executions_workflow_type'), 'workflow_executions', ['workflow_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_executions_workflow_type'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_agent_executions_created_at'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_name'), table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
