"""add_chat_tables

Revision ID: 79b66ba4fa2c
Revises: 30b18a0564e2
Create Date: 2026-01-30 15:34:17.827923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79b66ba4fa2c'
down_revision: Union[str, None] = '30b18a0564e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='会话唯一标识'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='系统用户ID'),
    sa.Column('external_user_id', sa.String(length=100), nullable=True, comment='外部用户ID（如飞书open_id）'),
    sa.Column('source', sa.String(length=20), nullable=False, comment='来源渠道：chatbox/feishu'),
    sa.Column('feishu_chat_id', sa.String(length=100), nullable=True, comment='飞书群/私聊ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='会话标题'),
    sa.Column('agent_id', sa.String(length=50), nullable=False, comment='使用的Agent'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否活跃'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_external_user_id'), 'chat_sessions', ['external_user_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_feishu_chat_id'), 'chat_sessions', ['feishu_chat_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_source'), 'chat_sessions', ['source'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False, comment='消息唯一标识'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='关联会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='角色：user/assistant/system/tool'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('tool_calls', sa.JSON(), nullable=True, comment='工具调用记录'),
    sa.Column('tool_results', sa.JSON(), nullable=True, comment='工具执行结果'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending/streaming/completed/failed'),
    sa.Column('model', sa.String(length=50), nullable=True, comment='使用的模型'),
    sa.Column('tokens_used', sa.Integer(), nullable=True, comment='消耗的Token数'),
    sa.Column('external_message_id', sa.String(length=100), nullable=True, comment='外部消息ID（如飞书消息ID）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_session_time', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index('idx_message_session_time', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_source'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_feishu_chat_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_external_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
