"""add worker_configs table

Revision ID: 80a92ad83752
Revises: b109c1d44fa9
Create Date: 2026-01-30 21:49:34.112217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a92ad83752'
down_revision: Union[str, None] = 'b109c1d44fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('worker_type', sa.String(length=20), nullable=False, comment='Worker 类型: feishu / email / dingtalk / wecom'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="显示名称，如'客服机器人'"),
    sa.Column('config', sa.JSON(), nullable=False, comment='配置数据（JSON）'),
    sa.Column('agent_id', sa.String(length=50), nullable=False, comment='绑定的 Agent ID'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述信息'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_configs_worker_type'), 'worker_configs', ['worker_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_configs_worker_type'), table_name='worker_configs')
    op.drop_table('worker_configs')
    # ### end Alembic commands ###
