"""add prompt tables

Revision ID: 8a46041980a2
Revises: 4c9b36b333c5
Create Date: 2026-01-30 13:21:00.394237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a46041980a2'
down_revision: Union[str, None] = '4c9b36b333c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_history',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('prompt_id', sa.UUID(), nullable=False, comment='原 Prompt ID'),
    sa.Column('prompt_name', sa.String(length=100), nullable=False, comment='Prompt 名称（冗余存储，防止原记录删除）'),
    sa.Column('content', sa.Text(), nullable=False, comment='历史版本内容'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='历史版本变量'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('changed_at', sa.DateTime(), nullable=False, comment='修改时间'),
    sa.Column('changed_by', sa.UUID(), nullable=True, comment='修改者用户ID'),
    sa.Column('change_reason', sa.String(length=500), nullable=True, comment='修改原因'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_history_prompt_id'), 'prompt_history', ['prompt_id'], unique=False)
    op.create_index('ix_prompt_history_version', 'prompt_history', ['prompt_id', 'version'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Prompt 名称（代码标识符）'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类：agent, tool, system, chat'),
    sa.Column('display_name', sa.String(length=200), nullable=True, comment='显示名称（中文）'),
    sa.Column('content', sa.Text(), nullable=False, comment='Prompt 模板内容'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='变量定义 {变量名: 说明}'),
    sa.Column('description', sa.Text(), nullable=True, comment='用途说明'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('model_hint', sa.String(length=50), nullable=True, comment='建议使用的模型：claude-3-opus, gpt-4, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建者用户ID'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='最后修改者用户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prompts_active', 'prompts', ['is_active'], unique=False)
    op.create_index('ix_prompts_category', 'prompts', ['category'], unique=False)
    op.create_index(op.f('ix_prompts_name'), 'prompts', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_name'), table_name='prompts')
    op.drop_index('ix_prompts_category', table_name='prompts')
    op.drop_index('ix_prompts_active', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index('ix_prompt_history_version', table_name='prompt_history')
    op.drop_index(op.f('ix_prompt_history_prompt_id'), table_name='prompt_history')
    op.drop_table('prompt_history')
    # ### end Alembic commands ###
