"""add_email_accounts_table

Revision ID: b109c1d44fa9
Revises: a1b2c3d4e5f6
Create Date: 2026-01-30 20:12:29.008675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b109c1d44fa9'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='账户名称'),
    sa.Column('purpose', sa.String(length=50), nullable=False, comment='用途: sales/support/notification/general'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('smtp_host', sa.String(length=200), nullable=False, comment='SMTP 服务器地址'),
    sa.Column('smtp_port', sa.Integer(), nullable=False, comment='SMTP 端口'),
    sa.Column('smtp_user', sa.String(length=200), nullable=False, comment='SMTP 用户名/邮箱'),
    sa.Column('smtp_password', sa.String(length=500), nullable=False, comment='SMTP 密码（加密存储）'),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False, comment='是否使用 TLS'),
    sa.Column('imap_host', sa.String(length=200), nullable=True, comment='IMAP 服务器地址'),
    sa.Column('imap_port', sa.Integer(), nullable=False, comment='IMAP 端口'),
    sa.Column('imap_user', sa.String(length=200), nullable=True, comment='IMAP 用户名/邮箱'),
    sa.Column('imap_password', sa.String(length=500), nullable=True, comment='IMAP 密码（加密存储）'),
    sa.Column('imap_use_ssl', sa.Boolean(), nullable=False, comment='是否使用 SSL'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认邮箱'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_purpose'), 'email_accounts', ['purpose'], unique=False)
    op.alter_column('events', 'source_id',
               existing_type=sa.VARCHAR(length=255),
               comment='原始消息 ID',
               existing_comment='原始消息ID',
               existing_nullable=True)
    op.alter_column('events', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='系统用户 ID',
               existing_comment='系统用户ID',
               existing_nullable=True)
    op.alter_column('events', 'user_external_id',
               existing_type=sa.VARCHAR(length=255),
               comment='外部用户 ID（邮箱/open_id 等）',
               existing_comment='外部用户ID（邮箱/open_id等）',
               existing_nullable=True)
    op.alter_column('events', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               comment='会话 ID',
               existing_comment='会话ID',
               existing_nullable=True)
    op.alter_column('events', 'thread_id',
               existing_type=sa.VARCHAR(length=255),
               comment='线程 ID（邮件回复链）',
               existing_comment='线程ID（邮件回复链）',
               existing_nullable=True)
    op.alter_column('events', 'workflow_id',
               existing_type=sa.VARCHAR(length=255),
               comment='关联的 Workflow ID',
               existing_comment='关联的Workflow ID',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'workflow_id',
               existing_type=sa.VARCHAR(length=255),
               comment='关联的Workflow ID',
               existing_comment='关联的 Workflow ID',
               existing_nullable=True)
    op.alter_column('events', 'thread_id',
               existing_type=sa.VARCHAR(length=255),
               comment='线程ID（邮件回复链）',
               existing_comment='线程 ID（邮件回复链）',
               existing_nullable=True)
    op.alter_column('events', 'session_id',
               existing_type=sa.VARCHAR(length=36),
               comment='会话ID',
               existing_comment='会话 ID',
               existing_nullable=True)
    op.alter_column('events', 'user_external_id',
               existing_type=sa.VARCHAR(length=255),
               comment='外部用户ID（邮箱/open_id等）',
               existing_comment='外部用户 ID（邮箱/open_id 等）',
               existing_nullable=True)
    op.alter_column('events', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='系统用户ID',
               existing_comment='系统用户 ID',
               existing_nullable=True)
    op.alter_column('events', 'source_id',
               existing_type=sa.VARCHAR(length=255),
               comment='原始消息ID',
               existing_comment='原始消息 ID',
               existing_nullable=True)
    op.drop_index(op.f('ix_email_accounts_purpose'), table_name='email_accounts')
    op.drop_table('email_accounts')
    # ### end Alembic commands ###
