"""add countries table

Revision ID: d3e4f5g6h7i8
Revises: c2d3e4f5a6b7
Create Date: 2026-02-08

创建国家/地区基础数据表（只读，系统预置）
包含 ISO 3166-1 标准信息、中英文名称、国际区号和货币信息
"""
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e4f5g6h7i8'
down_revision: Union[str, None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 创建 countries 表
    countries_table = op.create_table(
        'countries',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('name_zh', sa.String(100), nullable=False, comment='中文简称'),
        sa.Column('name_en', sa.String(100), nullable=False, comment='英文简称'),
        sa.Column('full_name_zh', sa.String(200), nullable=True, comment='中文全称'),
        sa.Column('full_name_en', sa.String(200), nullable=True, comment='英文全称'),
        sa.Column('iso_code_2', sa.String(2), nullable=False, comment='ISO 3166-1 alpha-2'),
        sa.Column('iso_code_3', sa.String(3), nullable=True, comment='ISO 3166-1 alpha-3'),
        sa.Column('numeric_code', sa.String(3), nullable=True, comment='ISO 3166-1 数字代码'),
        sa.Column('phone_code', sa.String(20), nullable=True, comment='国际电话区号'),
        sa.Column('currency_name_zh', sa.String(100), nullable=True, comment='货币中文名'),
        sa.Column('currency_name_en', sa.String(100), nullable=True, comment='货币英文名'),
        sa.Column('currency_code', sa.String(3), nullable=True, comment='货币代码 ISO 4217'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('iso_code_2'),
    )

    # 创建索引
    op.create_index('ix_countries_iso_code_2', 'countries', ['iso_code_2'], unique=True)
    op.create_index('ix_countries_name_zh', 'countries', ['name_zh'])
    op.create_index('ix_countries_name_en', 'countries', ['name_en'])

    # 灌入全部国家/地区数据
    op.bulk_insert(countries_table, [
        _c("阿富汗", "Afghanistan", "阿富汗伊斯兰共和国", "Islamic Republic of Afghanistan", "AF", "AFG", "004", "+93", "阿富汗尼", "Afghan Afghani", "AFN"),
        _c("阿尔巴尼亚", "Albania", "阿尔巴尼亚共和国", "Republic of Albania", "AL", "ALB", "008", "+355", "列克", "Albanian Lek", "ALL"),
        _c("阿尔及利亚", "Algeria", "阿尔及利亚民主人民共和国", "People's Democratic Republic of Algeria", "DZ", "DZA", "012", "+213", "阿尔及利亚第纳尔", "Algerian Dinar", "DZD"),
        _c("美属萨摩亚", "American Samoa", "美属萨摩亚", "American Samoa", "AS", "ASM", "016", "+1684", "美元", "US Dollar", "USD"),
        _c("安道尔", "Andorra", "安道尔公国", "Principality of Andorra", "AD", "AND", "020", "+376", "欧元", "Euro", "EUR"),
        _c("安哥拉", "Angola", "安哥拉共和国", "Republic of Angola", "AO", "AGO", "024", "+244", "宽扎", "Angolan Kwanza", "AOA"),
        _c("安圭拉", "Anguilla", "安圭拉", "Anguilla", "AI", "AIA", "660", "+1264", "东加勒比元", "East Caribbean Dollar", "XCD"),
        _c("安提瓜和巴布达", "Antigua and Barbuda", "安提瓜和巴布达", "Antigua and Barbuda", "AG", "ATG", "028", "+1268", "东加勒比元", "East Caribbean Dollar", "XCD"),
        _c("阿根廷", "Argentina", "阿根廷共和国", "Argentine Republic", "AR", "ARG", "032", "+54", "阿根廷比索", "Argentine Peso", "ARS"),
        _c("亚美尼亚", "Armenia", "亚美尼亚共和国", "Republic of Armenia", "AM", "ARM", "051", "+374", "德拉姆", "Armenian Dram", "AMD"),
        _c("阿鲁巴", "Aruba", "阿鲁巴", "Aruba", "AW", "ABW", "533", "+297", "阿鲁巴弗罗林", "Aruban Florin", "AWG"),
        _c("澳大利亚", "Australia", "澳大利亚联邦", "Commonwealth of Australia", "AU", "AUS", "036", "+61", "澳大利亚元", "Australian Dollar", "AUD"),
        _c("奥地利", "Austria", "奥地利共和国", "Republic of Austria", "AT", "AUT", "040", "+43", "欧元", "Euro", "EUR"),
        _c("阿塞拜疆", "Azerbaijan", "阿塞拜疆共和国", "Republic of Azerbaijan", "AZ", "AZE", "031", "+994", "马纳特", "Azerbaijani Manat", "AZN"),
        _c("巴哈马", "Bahamas", "巴哈马国", "Commonwealth of The Bahamas", "BS", "BHS", "044", "+1242", "巴哈马元", "Bahamian Dollar", "BSD"),
        _c("巴林", "Bahrain", "巴林王国", "Kingdom of Bahrain", "BH", "BHR", "048", "+973", "巴林第纳尔", "Bahraini Dinar", "BHD"),
        _c("孟加拉国", "Bangladesh", "孟加拉人民共和国", "People's Republic of Bangladesh", "BD", "BGD", "050", "+880", "塔卡", "Bangladeshi Taka", "BDT"),
        _c("巴巴多斯", "Barbados", "巴巴多斯", "Barbados", "BB", "BRB", "052", "+1246", "巴巴多斯元", "Barbadian Dollar", "BBD"),
        _c("白俄罗斯", "Belarus", "白俄罗斯共和国", "Republic of Belarus", "BY", "BLR", "112", "+375", "白俄罗斯卢布", "Belarusian Ruble", "BYN"),
        _c("比利时", "Belgium", "比利时王国", "Kingdom of Belgium", "BE", "BEL", "056", "+32", "欧元", "Euro", "EUR"),
        _c("伯利兹", "Belize", "伯利兹", "Belize", "BZ", "BLZ", "084", "+501", "伯利兹元", "Belize Dollar", "BZD"),
        _c("贝宁", "Benin", "贝宁共和国", "Republic of Benin", "BJ", "BEN", "204", "+229", "西非法郎", "West African CFA Franc", "XOF"),
        _c("百慕大", "Bermuda", "百慕大", "Bermuda", "BM", "BMU", "060", "+1441", "百慕大元", "Bermudian Dollar", "BMD"),
        _c("不丹", "Bhutan", "不丹王国", "Kingdom of Bhutan", "BT", "BTN", "064", "+975", "努尔特鲁姆", "Bhutanese Ngultrum", "BTN"),
        _c("玻利维亚", "Bolivia", "多民族玻利维亚国", "Plurinational State of Bolivia", "BO", "BOL", "068", "+591", "玻利维亚诺", "Bolivian Boliviano", "BOB"),
        _c("波黑", "Bosnia and Herzegovina", "波斯尼亚和黑塞哥维那", "Bosnia and Herzegovina", "BA", "BIH", "070", "+387", "可兑换马克", "Bosnia-Herzegovina Convertible Mark", "BAM"),
        _c("博茨瓦纳", "Botswana", "博茨瓦纳共和国", "Republic of Botswana", "BW", "BWA", "072", "+267", "普拉", "Botswanan Pula", "BWP"),
        _c("巴西", "Brazil", "巴西联邦共和国", "Federative Republic of Brazil", "BR", "BRA", "076", "+55", "巴西雷亚尔", "Brazilian Real", "BRL"),
        _c("英属维尔京群岛", "British Virgin Islands", "英属维尔京群岛", "British Virgin Islands", "VG", "VGB", "092", "+1284", "美元", "US Dollar", "USD"),
        _c("文莱", "Brunei", "文莱达鲁萨兰国", "Brunei Darussalam", "BN", "BRN", "096", "+673", "文莱元", "Brunei Dollar", "BND"),
        _c("保加利亚", "Bulgaria", "保加利亚共和国", "Republic of Bulgaria", "BG", "BGR", "100", "+359", "列弗", "Bulgarian Lev", "BGN"),
        _c("布基纳法索", "Burkina Faso", "布基纳法索", "Burkina Faso", "BF", "BFA", "854", "+226", "西非法郎", "West African CFA Franc", "XOF"),
        _c("布隆迪", "Burundi", "布隆迪共和国", "Republic of Burundi", "BI", "BDI", "108", "+257", "布隆迪法郎", "Burundian Franc", "BIF"),
        _c("佛得角", "Cabo Verde", "佛得角共和国", "Republic of Cabo Verde", "CV", "CPV", "132", "+238", "佛得角埃斯库多", "Cape Verdean Escudo", "CVE"),
        _c("柬埔寨", "Cambodia", "柬埔寨王国", "Kingdom of Cambodia", "KH", "KHM", "116", "+855", "瑞尔", "Cambodian Riel", "KHR"),
        _c("喀麦隆", "Cameroon", "喀麦隆共和国", "Republic of Cameroon", "CM", "CMR", "120", "+237", "中非法郎", "Central African CFA Franc", "XAF"),
        _c("加拿大", "Canada", "加拿大", "Canada", "CA", "CAN", "124", "+1", "加拿大元", "Canadian Dollar", "CAD"),
        _c("开曼群岛", "Cayman Islands", "开曼群岛", "Cayman Islands", "KY", "CYM", "136", "+1345", "开曼群岛元", "Cayman Islands Dollar", "KYD"),
        _c("中非", "Central African Republic", "中非共和国", "Central African Republic", "CF", "CAF", "140", "+236", "中非法郎", "Central African CFA Franc", "XAF"),
        _c("乍得", "Chad", "乍得共和国", "Republic of Chad", "TD", "TCD", "148", "+235", "中非法郎", "Central African CFA Franc", "XAF"),
        _c("智利", "Chile", "智利共和国", "Republic of Chile", "CL", "CHL", "152", "+56", "智利比索", "Chilean Peso", "CLP"),
        _c("中国", "China", "中华人民共和国", "People's Republic of China", "CN", "CHN", "156", "+86", "人民币", "Chinese Yuan", "CNY"),
        _c("哥伦比亚", "Colombia", "哥伦比亚共和国", "Republic of Colombia", "CO", "COL", "170", "+57", "哥伦比亚比索", "Colombian Peso", "COP"),
        _c("科摩罗", "Comoros", "科摩罗联盟", "Union of the Comoros", "KM", "COM", "174", "+269", "科摩罗法郎", "Comorian Franc", "KMF"),
        _c("刚果（布）", "Congo", "刚果共和国", "Republic of the Congo", "CG", "COG", "178", "+242", "中非法郎", "Central African CFA Franc", "XAF"),
        _c("刚果（金）", "Congo (DRC)", "刚果民主共和国", "Democratic Republic of the Congo", "CD", "COD", "180", "+243", "刚果法郎", "Congolese Franc", "CDF"),
        _c("库克群岛", "Cook Islands", "库克群岛", "Cook Islands", "CK", "COK", "184", "+682", "新西兰元", "New Zealand Dollar", "NZD"),
        _c("哥斯达黎加", "Costa Rica", "哥斯达黎加共和国", "Republic of Costa Rica", "CR", "CRI", "188", "+506", "哥斯达黎加科朗", "Costa Rican Colón", "CRC"),
        _c("科特迪瓦", "Côte d'Ivoire", "科特迪瓦共和国", "Republic of Côte d'Ivoire", "CI", "CIV", "384", "+225", "西非法郎", "West African CFA Franc", "XOF"),
        _c("克罗地亚", "Croatia", "克罗地亚共和国", "Republic of Croatia", "HR", "HRV", "191", "+385", "欧元", "Euro", "EUR"),
        _c("古巴", "Cuba", "古巴共和国", "Republic of Cuba", "CU", "CUB", "192", "+53", "古巴比索", "Cuban Peso", "CUP"),
        _c("库拉索", "Curaçao", "库拉索", "Curaçao", "CW", "CUW", "531", "+5999", "荷属安的列斯盾", "Netherlands Antillean Guilder", "ANG"),
        _c("塞浦路斯", "Cyprus", "塞浦路斯共和国", "Republic of Cyprus", "CY", "CYP", "196", "+357", "欧元", "Euro", "EUR"),
        _c("捷克", "Czech Republic", "捷克共和国", "Czech Republic", "CZ", "CZE", "203", "+420", "捷克克朗", "Czech Koruna", "CZK"),
        _c("丹麦", "Denmark", "丹麦王国", "Kingdom of Denmark", "DK", "DNK", "208", "+45", "丹麦克朗", "Danish Krone", "DKK"),
        _c("吉布提", "Djibouti", "吉布提共和国", "Republic of Djibouti", "DJ", "DJI", "262", "+253", "吉布提法郎", "Djiboutian Franc", "DJF"),
        _c("多米尼克", "Dominica", "多米尼克国", "Commonwealth of Dominica", "DM", "DMA", "212", "+1767", "东加勒比元", "East Caribbean Dollar", "XCD"),
        _c("多米尼加", "Dominican Republic", "多米尼加共和国", "Dominican Republic", "DO", "DOM", "214", "+1809", "多米尼加比索", "Dominican Peso", "DOP"),
        _c("厄瓜多尔", "Ecuador", "厄瓜多尔共和国", "Republic of Ecuador", "EC", "ECU", "218", "+593", "美元", "US Dollar", "USD"),
        _c("埃及", "Egypt", "阿拉伯埃及共和国", "Arab Republic of Egypt", "EG", "EGY", "818", "+20", "埃及镑", "Egyptian Pound", "EGP"),
        _c("萨尔瓦多", "El Salvador", "萨尔瓦多共和国", "Republic of El Salvador", "SV", "SLV", "222", "+503", "美元", "US Dollar", "USD"),
        _c("赤道几内亚", "Equatorial Guinea", "赤道几内亚共和国", "Republic of Equatorial Guinea", "GQ", "GNQ", "226", "+240", "中非法郎", "Central African CFA Franc", "XAF"),
        _c("厄立特里亚", "Eritrea", "厄立特里亚国", "State of Eritrea", "ER", "ERI", "232", "+291", "纳克法", "Eritrean Nakfa", "ERN"),
        _c("爱沙尼亚", "Estonia", "爱沙尼亚共和国", "Republic of Estonia", "EE", "EST", "233", "+372", "欧元", "Euro", "EUR"),
        _c("斯威士兰", "Eswatini", "斯威士兰王国", "Kingdom of Eswatini", "SZ", "SWZ", "748", "+268", "里兰吉尼", "Swazi Lilangeni", "SZL"),
        _c("埃塞俄比亚", "Ethiopia", "埃塞俄比亚联邦民主共和国", "Federal Democratic Republic of Ethiopia", "ET", "ETH", "231", "+251", "比尔", "Ethiopian Birr", "ETB"),
        _c("福克兰群岛", "Falkland Islands", "福克兰群岛", "Falkland Islands", "FK", "FLK", "238", "+500", "福克兰群岛镑", "Falkland Islands Pound", "FKP"),
        _c("法罗群岛", "Faroe Islands", "法罗群岛", "Faroe Islands", "FO", "FRO", "234", "+298", "丹麦克朗", "Danish Krone", "DKK"),
        _c("斐济", "Fiji", "斐济共和国", "Republic of Fiji", "FJ", "FJI", "242", "+679", "斐济元", "Fijian Dollar", "FJD"),
        _c("芬兰", "Finland", "芬兰共和国", "Republic of Finland", "FI", "FIN", "246", "+358", "欧元", "Euro", "EUR"),
        _c("法国", "France", "法兰西共和国", "French Republic", "FR", "FRA", "250", "+33", "欧元", "Euro", "EUR"),
        _c("法属圭亚那", "French Guiana", "法属圭亚那", "French Guiana", "GF", "GUF", "254", "+594", "欧元", "Euro", "EUR"),
        _c("法属波利尼西亚", "French Polynesia", "法属波利尼西亚", "French Polynesia", "PF", "PYF", "258", "+689", "太平洋法郎", "CFP Franc", "XPF"),
        _c("加蓬", "Gabon", "加蓬共和国", "Gabonese Republic", "GA", "GAB", "266", "+241", "中非法郎", "Central African CFA Franc", "XAF"),
        _c("冈比亚", "Gambia", "冈比亚共和国", "Republic of The Gambia", "GM", "GMB", "270", "+220", "达拉西", "Gambian Dalasi", "GMD"),
        _c("格鲁吉亚", "Georgia", "格鲁吉亚", "Georgia", "GE", "GEO", "268", "+995", "拉里", "Georgian Lari", "GEL"),
        _c("德国", "Germany", "德意志联邦共和国", "Federal Republic of Germany", "DE", "DEU", "276", "+49", "欧元", "Euro", "EUR"),
        _c("加纳", "Ghana", "加纳共和国", "Republic of Ghana", "GH", "GHA", "288", "+233", "塞地", "Ghanaian Cedi", "GHS"),
        _c("直布罗陀", "Gibraltar", "直布罗陀", "Gibraltar", "GI", "GIB", "292", "+350", "直布罗陀镑", "Gibraltar Pound", "GIP"),
        _c("希腊", "Greece", "希腊共和国", "Hellenic Republic", "GR", "GRC", "300", "+30", "欧元", "Euro", "EUR"),
        _c("格陵兰", "Greenland", "格陵兰", "Greenland", "GL", "GRL", "304", "+299", "丹麦克朗", "Danish Krone", "DKK"),
        _c("格林纳达", "Grenada", "格林纳达", "Grenada", "GD", "GRD", "308", "+1473", "东加勒比元", "East Caribbean Dollar", "XCD"),
        _c("瓜德罗普", "Guadeloupe", "瓜德罗普", "Guadeloupe", "GP", "GLP", "312", "+590", "欧元", "Euro", "EUR"),
        _c("关岛", "Guam", "关岛", "Guam", "GU", "GUM", "316", "+1671", "美元", "US Dollar", "USD"),
        _c("危地马拉", "Guatemala", "危地马拉共和国", "Republic of Guatemala", "GT", "GTM", "320", "+502", "格查尔", "Guatemalan Quetzal", "GTQ"),
        _c("根西岛", "Guernsey", "根西岛", "Bailiwick of Guernsey", "GG", "GGY", "831", "+44", "英镑", "British Pound", "GBP"),
        _c("几内亚", "Guinea", "几内亚共和国", "Republic of Guinea", "GN", "GIN", "324", "+224", "几内亚法郎", "Guinean Franc", "GNF"),
        _c("几内亚比绍", "Guinea-Bissau", "几内亚比绍共和国", "Republic of Guinea-Bissau", "GW", "GNB", "624", "+245", "西非法郎", "West African CFA Franc", "XOF"),
        _c("圭亚那", "Guyana", "圭亚那合作共和国", "Co-operative Republic of Guyana", "GY", "GUY", "328", "+592", "圭亚那元", "Guyanese Dollar", "GYD"),
        _c("海地", "Haiti", "海地共和国", "Republic of Haiti", "HT", "HTI", "332", "+509", "古德", "Haitian Gourde", "HTG"),
        _c("洪都拉斯", "Honduras", "洪都拉斯共和国", "Republic of Honduras", "HN", "HND", "340", "+504", "伦皮拉", "Honduran Lempira", "HNL"),
        _c("香港", "Hong Kong", "中国香港特别行政区", "Hong Kong Special Administrative Region of China", "HK", "HKG", "344", "+852", "港元", "Hong Kong Dollar", "HKD"),
        _c("匈牙利", "Hungary", "匈牙利", "Hungary", "HU", "HUN", "348", "+36", "福林", "Hungarian Forint", "HUF"),
        _c("冰岛", "Iceland", "冰岛共和国", "Republic of Iceland", "IS", "ISL", "352", "+354", "冰岛克朗", "Icelandic Króna", "ISK"),
        _c("印度", "India", "印度共和国", "Republic of India", "IN", "IND", "356", "+91", "印度卢比", "Indian Rupee", "INR"),
        _c("印度尼西亚", "Indonesia", "印度尼西亚共和国", "Republic of Indonesia", "ID", "IDN", "360", "+62", "印尼卢比", "Indonesian Rupiah", "IDR"),
        _c("伊朗", "Iran", "伊朗伊斯兰共和国", "Islamic Republic of Iran", "IR", "IRN", "364", "+98", "伊朗里亚尔", "Iranian Rial", "IRR"),
        _c("伊拉克", "Iraq", "伊拉克共和国", "Republic of Iraq", "IQ", "IRQ", "368", "+964", "伊拉克第纳尔", "Iraqi Dinar", "IQD"),
        _c("爱尔兰", "Ireland", "爱尔兰", "Ireland", "IE", "IRL", "372", "+353", "欧元", "Euro", "EUR"),
        _c("马恩岛", "Isle of Man", "马恩岛", "Isle of Man", "IM", "IMN", "833", "+44", "英镑", "British Pound", "GBP"),
        _c("以色列", "Israel", "以色列国", "State of Israel", "IL", "ISR", "376", "+972", "新谢克尔", "Israeli New Shekel", "ILS"),
        _c("意大利", "Italy", "意大利共和国", "Italian Republic", "IT", "ITA", "380", "+39", "欧元", "Euro", "EUR"),
        _c("牙买加", "Jamaica", "牙买加", "Jamaica", "JM", "JAM", "388", "+1876", "牙买加元", "Jamaican Dollar", "JMD"),
        _c("日本", "Japan", "日本国", "Japan", "JP", "JPN", "392", "+81", "日元", "Japanese Yen", "JPY"),
        _c("泽西岛", "Jersey", "泽西岛", "Bailiwick of Jersey", "JE", "JEY", "832", "+44", "英镑", "British Pound", "GBP"),
        _c("约旦", "Jordan", "约旦哈希姆王国", "Hashemite Kingdom of Jordan", "JO", "JOR", "400", "+962", "约旦第纳尔", "Jordanian Dinar", "JOD"),
        _c("哈萨克斯坦", "Kazakhstan", "哈萨克斯坦共和国", "Republic of Kazakhstan", "KZ", "KAZ", "398", "+7", "坚戈", "Kazakhstani Tenge", "KZT"),
        _c("肯尼亚", "Kenya", "肯尼亚共和国", "Republic of Kenya", "KE", "KEN", "404", "+254", "肯尼亚先令", "Kenyan Shilling", "KES"),
        _c("基里巴斯", "Kiribati", "基里巴斯共和国", "Republic of Kiribati", "KI", "KIR", "296", "+686", "澳大利亚元", "Australian Dollar", "AUD"),
        _c("科威特", "Kuwait", "科威特国", "State of Kuwait", "KW", "KWT", "414", "+965", "科威特第纳尔", "Kuwaiti Dinar", "KWD"),
        _c("吉尔吉斯斯坦", "Kyrgyzstan", "吉尔吉斯共和国", "Kyrgyz Republic", "KG", "KGZ", "417", "+996", "索姆", "Kyrgystani Som", "KGS"),
        _c("老挝", "Laos", "老挝人民民主共和国", "Lao People's Democratic Republic", "LA", "LAO", "418", "+856", "基普", "Lao Kip", "LAK"),
        _c("拉脱维亚", "Latvia", "拉脱维亚共和国", "Republic of Latvia", "LV", "LVA", "428", "+371", "欧元", "Euro", "EUR"),
        _c("黎巴嫩", "Lebanon", "黎巴嫩共和国", "Lebanese Republic", "LB", "LBN", "422", "+961", "黎巴嫩镑", "Lebanese Pound", "LBP"),
        _c("莱索托", "Lesotho", "莱索托王国", "Kingdom of Lesotho", "LS", "LSO", "426", "+266", "洛蒂", "Lesotho Loti", "LSL"),
        _c("利比里亚", "Liberia", "利比里亚共和国", "Republic of Liberia", "LR", "LBR", "430", "+231", "利比里亚元", "Liberian Dollar", "LRD"),
        _c("利比亚", "Libya", "利比亚国", "State of Libya", "LY", "LBY", "434", "+218", "利比亚第纳尔", "Libyan Dinar", "LYD"),
        _c("列支敦士登", "Liechtenstein", "列支敦士登公国", "Principality of Liechtenstein", "LI", "LIE", "438", "+423", "瑞士法郎", "Swiss Franc", "CHF"),
        _c("立陶宛", "Lithuania", "立陶宛共和国", "Republic of Lithuania", "LT", "LTU", "440", "+370", "欧元", "Euro", "EUR"),
        _c("卢森堡", "Luxembourg", "卢森堡大公国", "Grand Duchy of Luxembourg", "LU", "LUX", "442", "+352", "欧元", "Euro", "EUR"),
        _c("澳门", "Macau", "中国澳门特别行政区", "Macao Special Administrative Region of China", "MO", "MAC", "446", "+853", "澳门元", "Macanese Pataca", "MOP"),
        _c("马达加斯加", "Madagascar", "马达加斯加共和国", "Republic of Madagascar", "MG", "MDG", "450", "+261", "阿里亚里", "Malagasy Ariary", "MGA"),
        _c("马拉维", "Malawi", "马拉维共和国", "Republic of Malawi", "MW", "MWI", "454", "+265", "马拉维克瓦查", "Malawian Kwacha", "MWK"),
        _c("马来西亚", "Malaysia", "马来西亚", "Malaysia", "MY", "MYS", "458", "+60", "马来西亚林吉特", "Malaysian Ringgit", "MYR"),
        _c("马尔代夫", "Maldives", "马尔代夫共和国", "Republic of Maldives", "MV", "MDV", "462", "+960", "拉菲亚", "Maldivian Rufiyaa", "MVR"),
        _c("马里", "Mali", "马里共和国", "Republic of Mali", "ML", "MLI", "466", "+223", "西非法郎", "West African CFA Franc", "XOF"),
        _c("马耳他", "Malta", "马耳他共和国", "Republic of Malta", "MT", "MLT", "470", "+356", "欧元", "Euro", "EUR"),
        _c("马绍尔群岛", "Marshall Islands", "马绍尔群岛共和国", "Republic of the Marshall Islands", "MH", "MHL", "584", "+692", "美元", "US Dollar", "USD"),
        _c("马提尼克", "Martinique", "马提尼克", "Martinique", "MQ", "MTQ", "474", "+596", "欧元", "Euro", "EUR"),
        _c("毛里塔尼亚", "Mauritania", "毛里塔尼亚伊斯兰共和国", "Islamic Republic of Mauritania", "MR", "MRT", "478", "+222", "乌吉亚", "Mauritanian Ouguiya", "MRU"),
        _c("毛里求斯", "Mauritius", "毛里求斯共和国", "Republic of Mauritius", "MU", "MUS", "480", "+230", "毛里求斯卢比", "Mauritian Rupee", "MUR"),
        _c("马约特", "Mayotte", "马约特", "Mayotte", "YT", "MYT", "175", "+262", "欧元", "Euro", "EUR"),
        _c("墨西哥", "Mexico", "墨西哥合众国", "United Mexican States", "MX", "MEX", "484", "+52", "墨西哥比索", "Mexican Peso", "MXN"),
        _c("密克罗尼西亚", "Micronesia", "密克罗尼西亚联邦", "Federated States of Micronesia", "FM", "FSM", "583", "+691", "美元", "US Dollar", "USD"),
        _c("摩尔多瓦", "Moldova", "摩尔多瓦共和国", "Republic of Moldova", "MD", "MDA", "498", "+373", "摩尔多瓦列伊", "Moldovan Leu", "MDL"),
        _c("摩纳哥", "Monaco", "摩纳哥公国", "Principality of Monaco", "MC", "MCO", "492", "+377", "欧元", "Euro", "EUR"),
        _c("蒙古", "Mongolia", "蒙古国", "Mongolia", "MN", "MNG", "496", "+976", "图格里克", "Mongolian Tögrög", "MNT"),
        _c("黑山", "Montenegro", "黑山", "Montenegro", "ME", "MNE", "499", "+382", "欧元", "Euro", "EUR"),
        _c("蒙特塞拉特", "Montserrat", "蒙特塞拉特", "Montserrat", "MS", "MSR", "500", "+1664", "东加勒比元", "East Caribbean Dollar", "XCD"),
        _c("摩洛哥", "Morocco", "摩洛哥王国", "Kingdom of Morocco", "MA", "MAR", "504", "+212", "摩洛哥迪拉姆", "Moroccan Dirham", "MAD"),
        _c("莫桑比克", "Mozambique", "莫桑比克共和国", "Republic of Mozambique", "MZ", "MOZ", "508", "+258", "梅蒂卡尔", "Mozambican Metical", "MZN"),
        _c("缅甸", "Myanmar", "缅甸联邦共和国", "Republic of the Union of Myanmar", "MM", "MMR", "104", "+95", "缅元", "Myanmar Kyat", "MMK"),
        _c("纳米比亚", "Namibia", "纳米比亚共和国", "Republic of Namibia", "NA", "NAM", "516", "+264", "纳米比亚元", "Namibian Dollar", "NAD"),
        _c("瑙鲁", "Nauru", "瑙鲁共和国", "Republic of Nauru", "NR", "NRU", "520", "+674", "澳大利亚元", "Australian Dollar", "AUD"),
        _c("尼泊尔", "Nepal", "尼泊尔联邦民主共和国", "Federal Democratic Republic of Nepal", "NP", "NPL", "524", "+977", "尼泊尔卢比", "Nepalese Rupee", "NPR"),
        _c("荷兰", "Netherlands", "荷兰王国", "Kingdom of the Netherlands", "NL", "NLD", "528", "+31", "欧元", "Euro", "EUR"),
        _c("新喀里多尼亚", "New Caledonia", "新喀里多尼亚", "New Caledonia", "NC", "NCL", "540", "+687", "太平洋法郎", "CFP Franc", "XPF"),
        _c("新西兰", "New Zealand", "新西兰", "New Zealand", "NZ", "NZL", "554", "+64", "新西兰元", "New Zealand Dollar", "NZD"),
        _c("尼加拉瓜", "Nicaragua", "尼加拉瓜共和国", "Republic of Nicaragua", "NI", "NIC", "558", "+505", "科多巴", "Nicaraguan Córdoba", "NIO"),
        _c("尼日尔", "Niger", "尼日尔共和国", "Republic of Niger", "NE", "NER", "562", "+227", "西非法郎", "West African CFA Franc", "XOF"),
        _c("尼日利亚", "Nigeria", "尼日利亚联邦共和国", "Federal Republic of Nigeria", "NG", "NGA", "566", "+234", "奈拉", "Nigerian Naira", "NGN"),
        _c("纽埃", "Niue", "纽埃", "Niue", "NU", "NIU", "570", "+683", "新西兰元", "New Zealand Dollar", "NZD"),
        _c("诺福克岛", "Norfolk Island", "诺福克岛", "Norfolk Island", "NF", "NFK", "574", "+672", "澳大利亚元", "Australian Dollar", "AUD"),
        _c("朝鲜", "North Korea", "朝鲜民主主义人民共和国", "Democratic People's Republic of Korea", "KP", "PRK", "408", "+850", "朝鲜圆", "North Korean Won", "KPW"),
        _c("北马其顿", "North Macedonia", "北马其顿共和国", "Republic of North Macedonia", "MK", "MKD", "807", "+389", "代纳尔", "Macedonian Denar", "MKD"),
        _c("北马里亚纳群岛", "Northern Mariana Islands", "北马里亚纳群岛", "Commonwealth of the Northern Mariana Islands", "MP", "MNP", "580", "+1670", "美元", "US Dollar", "USD"),
        _c("挪威", "Norway", "挪威王国", "Kingdom of Norway", "NO", "NOR", "578", "+47", "挪威克朗", "Norwegian Krone", "NOK"),
        _c("阿曼", "Oman", "阿曼苏丹国", "Sultanate of Oman", "OM", "OMN", "512", "+968", "阿曼里亚尔", "Omani Rial", "OMR"),
        _c("巴基斯坦", "Pakistan", "巴基斯坦伊斯兰共和国", "Islamic Republic of Pakistan", "PK", "PAK", "586", "+92", "巴基斯坦卢比", "Pakistani Rupee", "PKR"),
        _c("帕劳", "Palau", "帕劳共和国", "Republic of Palau", "PW", "PLW", "585", "+680", "美元", "US Dollar", "USD"),
        _c("巴勒斯坦", "Palestine", "巴勒斯坦国", "State of Palestine", "PS", "PSE", "275", "+970", "新谢克尔", "Israeli New Shekel", "ILS"),
        _c("巴拿马", "Panama", "巴拿马共和国", "Republic of Panama", "PA", "PAN", "591", "+507", "巴波亚", "Panamanian Balboa", "PAB"),
        _c("巴布亚新几内亚", "Papua New Guinea", "巴布亚新几内亚独立国", "Independent State of Papua New Guinea", "PG", "PNG", "598", "+675", "基那", "Papua New Guinean Kina", "PGK"),
        _c("巴拉圭", "Paraguay", "巴拉圭共和国", "Republic of Paraguay", "PY", "PRY", "600", "+595", "瓜拉尼", "Paraguayan Guaraní", "PYG"),
        _c("秘鲁", "Peru", "秘鲁共和国", "Republic of Peru", "PE", "PER", "604", "+51", "索尔", "Peruvian Sol", "PEN"),
        _c("菲律宾", "Philippines", "菲律宾共和国", "Republic of the Philippines", "PH", "PHL", "608", "+63", "菲律宾比索", "Philippine Peso", "PHP"),
        _c("波兰", "Poland", "波兰共和国", "Republic of Poland", "PL", "POL", "616", "+48", "兹罗提", "Polish Złoty", "PLN"),
        _c("葡萄牙", "Portugal", "葡萄牙共和国", "Portuguese Republic", "PT", "PRT", "620", "+351", "欧元", "Euro", "EUR"),
        _c("波多黎各", "Puerto Rico", "波多黎各自由邦", "Commonwealth of Puerto Rico", "PR", "PRI", "630", "+1787", "美元", "US Dollar", "USD"),
        _c("卡塔尔", "Qatar", "卡塔尔国", "State of Qatar", "QA", "QAT", "634", "+974", "卡塔尔里亚尔", "Qatari Riyal", "QAR"),
        _c("留尼汪", "Réunion", "留尼汪", "Réunion", "RE", "REU", "638", "+262", "欧元", "Euro", "EUR"),
        _c("罗马尼亚", "Romania", "罗马尼亚", "Romania", "RO", "ROU", "642", "+40", "罗马尼亚列伊", "Romanian Leu", "RON"),
        _c("俄罗斯", "Russia", "俄罗斯联邦", "Russian Federation", "RU", "RUS", "643", "+7", "俄罗斯卢布", "Russian Ruble", "RUB"),
        _c("卢旺达", "Rwanda", "卢旺达共和国", "Republic of Rwanda", "RW", "RWA", "646", "+250", "卢旺达法郎", "Rwandan Franc", "RWF"),
        _c("圣巴泰勒米", "Saint Barthélemy", "圣巴泰勒米", "Saint Barthélemy", "BL", "BLM", "652", "+590", "欧元", "Euro", "EUR"),
        _c("圣赫勒拿", "Saint Helena", "圣赫勒拿、阿森松和特里斯坦-达库尼亚", "Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", "654", "+290", "圣赫勒拿镑", "Saint Helena Pound", "SHP"),
        _c("圣基茨和尼维斯", "Saint Kitts and Nevis", "圣基茨和尼维斯联邦", "Federation of Saint Christopher and Nevis", "KN", "KNA", "659", "+1869", "东加勒比元", "East Caribbean Dollar", "XCD"),
        _c("圣卢西亚", "Saint Lucia", "圣卢西亚", "Saint Lucia", "LC", "LCA", "662", "+1758", "东加勒比元", "East Caribbean Dollar", "XCD"),
        _c("圣马丁", "Saint Martin", "圣马丁", "Saint Martin", "MF", "MAF", "663", "+590", "欧元", "Euro", "EUR"),
        _c("圣皮埃尔和密克隆", "Saint Pierre and Miquelon", "圣皮埃尔和密克隆", "Saint Pierre and Miquelon", "PM", "SPM", "666", "+508", "欧元", "Euro", "EUR"),
        _c("圣文森特和格林纳丁斯", "Saint Vincent and the Grenadines", "圣文森特和格林纳丁斯", "Saint Vincent and the Grenadines", "VC", "VCT", "670", "+1784", "东加勒比元", "East Caribbean Dollar", "XCD"),
        _c("萨摩亚", "Samoa", "萨摩亚独立国", "Independent State of Samoa", "WS", "WSM", "882", "+685", "塔拉", "Samoan Tālā", "WST"),
        _c("圣马力诺", "San Marino", "圣马力诺共和国", "Republic of San Marino", "SM", "SMR", "674", "+378", "欧元", "Euro", "EUR"),
        _c("圣多美和普林西比", "São Tomé and Príncipe", "圣多美和普林西比民主共和国", "Democratic Republic of São Tomé and Príncipe", "ST", "STP", "678", "+239", "多布拉", "São Tomé and Príncipe Dobra", "STN"),
        _c("沙特阿拉伯", "Saudi Arabia", "沙特阿拉伯王国", "Kingdom of Saudi Arabia", "SA", "SAU", "682", "+966", "沙特里亚尔", "Saudi Riyal", "SAR"),
        _c("塞内加尔", "Senegal", "塞内加尔共和国", "Republic of Senegal", "SN", "SEN", "686", "+221", "西非法郎", "West African CFA Franc", "XOF"),
        _c("塞尔维亚", "Serbia", "塞尔维亚共和国", "Republic of Serbia", "RS", "SRB", "688", "+381", "塞尔维亚第纳尔", "Serbian Dinar", "RSD"),
        _c("塞舌尔", "Seychelles", "塞舌尔共和国", "Republic of Seychelles", "SC", "SYC", "690", "+248", "塞舌尔卢比", "Seychellois Rupee", "SCR"),
        _c("塞拉利昂", "Sierra Leone", "塞拉利昂共和国", "Republic of Sierra Leone", "SL", "SLE", "694", "+232", "利昂", "Sierra Leonean Leone", "SLE"),
        _c("新加坡", "Singapore", "新加坡共和国", "Republic of Singapore", "SG", "SGP", "702", "+65", "新加坡元", "Singapore Dollar", "SGD"),
        _c("荷属圣马丁", "Sint Maarten", "荷属圣马丁", "Sint Maarten", "SX", "SXM", "534", "+1721", "荷属安的列斯盾", "Netherlands Antillean Guilder", "ANG"),
        _c("斯洛伐克", "Slovakia", "斯洛伐克共和国", "Slovak Republic", "SK", "SVK", "703", "+421", "欧元", "Euro", "EUR"),
        _c("斯洛文尼亚", "Slovenia", "斯洛文尼亚共和国", "Republic of Slovenia", "SI", "SVN", "705", "+386", "欧元", "Euro", "EUR"),
        _c("所罗门群岛", "Solomon Islands", "所罗门群岛", "Solomon Islands", "SB", "SLB", "090", "+677", "所罗门群岛元", "Solomon Islands Dollar", "SBD"),
        _c("索马里", "Somalia", "索马里联邦共和国", "Federal Republic of Somalia", "SO", "SOM", "706", "+252", "索马里先令", "Somali Shilling", "SOS"),
        _c("南非", "South Africa", "南非共和国", "Republic of South Africa", "ZA", "ZAF", "710", "+27", "兰特", "South African Rand", "ZAR"),
        _c("韩国", "South Korea", "大韩民国", "Republic of Korea", "KR", "KOR", "410", "+82", "韩元", "South Korean Won", "KRW"),
        _c("南苏丹", "South Sudan", "南苏丹共和国", "Republic of South Sudan", "SS", "SSD", "728", "+211", "南苏丹镑", "South Sudanese Pound", "SSP"),
        _c("西班牙", "Spain", "西班牙王国", "Kingdom of Spain", "ES", "ESP", "724", "+34", "欧元", "Euro", "EUR"),
        _c("斯里兰卡", "Sri Lanka", "斯里兰卡民主社会主义共和国", "Democratic Socialist Republic of Sri Lanka", "LK", "LKA", "144", "+94", "斯里兰卡卢比", "Sri Lankan Rupee", "LKR"),
        _c("苏丹", "Sudan", "苏丹共和国", "Republic of the Sudan", "SD", "SDN", "729", "+249", "苏丹镑", "Sudanese Pound", "SDG"),
        _c("苏里南", "Suriname", "苏里南共和国", "Republic of Suriname", "SR", "SUR", "740", "+597", "苏里南元", "Surinamese Dollar", "SRD"),
        _c("瑞典", "Sweden", "瑞典王国", "Kingdom of Sweden", "SE", "SWE", "752", "+46", "瑞典克朗", "Swedish Krona", "SEK"),
        _c("瑞士", "Switzerland", "瑞士联邦", "Swiss Confederation", "CH", "CHE", "756", "+41", "瑞士法郎", "Swiss Franc", "CHF"),
        _c("叙利亚", "Syria", "阿拉伯叙利亚共和国", "Syrian Arab Republic", "SY", "SYR", "760", "+963", "叙利亚镑", "Syrian Pound", "SYP"),
        _c("台湾", "Taiwan", "中国台湾", "Taiwan, Province of China", "TW", "TWN", "158", "+886", "新台币", "New Taiwan Dollar", "TWD"),
        _c("塔吉克斯坦", "Tajikistan", "塔吉克斯坦共和国", "Republic of Tajikistan", "TJ", "TJK", "762", "+992", "索莫尼", "Tajikistani Somoni", "TJS"),
        _c("坦桑尼亚", "Tanzania", "坦桑尼亚联合共和国", "United Republic of Tanzania", "TZ", "TZA", "834", "+255", "坦桑尼亚先令", "Tanzanian Shilling", "TZS"),
        _c("泰国", "Thailand", "泰王国", "Kingdom of Thailand", "TH", "THA", "764", "+66", "泰铢", "Thai Baht", "THB"),
        _c("东帝汶", "Timor-Leste", "东帝汶民主共和国", "Democratic Republic of Timor-Leste", "TL", "TLS", "626", "+670", "美元", "US Dollar", "USD"),
        _c("多哥", "Togo", "多哥共和国", "Togolese Republic", "TG", "TGO", "768", "+228", "西非法郎", "West African CFA Franc", "XOF"),
        _c("汤加", "Tonga", "汤加王国", "Kingdom of Tonga", "TO", "TON", "776", "+676", "潘加", "Tongan Paʻanga", "TOP"),
        _c("特立尼达和多巴哥", "Trinidad and Tobago", "特立尼达和多巴哥共和国", "Republic of Trinidad and Tobago", "TT", "TTO", "780", "+1868", "特立尼达和多巴哥元", "Trinidad and Tobago Dollar", "TTD"),
        _c("突尼斯", "Tunisia", "突尼斯共和国", "Republic of Tunisia", "TN", "TUN", "788", "+216", "突尼斯第纳尔", "Tunisian Dinar", "TND"),
        _c("土耳其", "Turkey", "土耳其共和国", "Republic of Turkey", "TR", "TUR", "792", "+90", "土耳其里拉", "Turkish Lira", "TRY"),
        _c("土库曼斯坦", "Turkmenistan", "土库曼斯坦", "Turkmenistan", "TM", "TKM", "795", "+993", "马纳特", "Turkmenistan Manat", "TMT"),
        _c("特克斯和凯科斯群岛", "Turks and Caicos Islands", "特克斯和凯科斯群岛", "Turks and Caicos Islands", "TC", "TCA", "796", "+1649", "美元", "US Dollar", "USD"),
        _c("图瓦卢", "Tuvalu", "图瓦卢", "Tuvalu", "TV", "TUV", "798", "+688", "澳大利亚元", "Australian Dollar", "AUD"),
        _c("乌干达", "Uganda", "乌干达共和国", "Republic of Uganda", "UG", "UGA", "800", "+256", "乌干达先令", "Ugandan Shilling", "UGX"),
        _c("乌克兰", "Ukraine", "乌克兰", "Ukraine", "UA", "UKR", "804", "+380", "格里夫纳", "Ukrainian Hryvnia", "UAH"),
        _c("阿联酋", "United Arab Emirates", "阿拉伯联合酋长国", "United Arab Emirates", "AE", "ARE", "784", "+971", "阿联酋迪拉姆", "UAE Dirham", "AED"),
        _c("英国", "United Kingdom", "大不列颠及北爱尔兰联合王国", "United Kingdom of Great Britain and Northern Ireland", "GB", "GBR", "826", "+44", "英镑", "British Pound", "GBP"),
        _c("美国", "United States", "美利坚合众国", "United States of America", "US", "USA", "840", "+1", "美元", "US Dollar", "USD"),
        _c("乌拉圭", "Uruguay", "乌拉圭东岸共和国", "Oriental Republic of Uruguay", "UY", "URY", "858", "+598", "乌拉圭比索", "Uruguayan Peso", "UYU"),
        _c("乌兹别克斯坦", "Uzbekistan", "乌兹别克斯坦共和国", "Republic of Uzbekistan", "UZ", "UZB", "860", "+998", "索姆", "Uzbekistani Som", "UZS"),
        _c("瓦努阿图", "Vanuatu", "瓦努阿图共和国", "Republic of Vanuatu", "VU", "VUT", "548", "+678", "瓦图", "Vanuatu Vatu", "VUV"),
        _c("梵蒂冈", "Vatican City", "梵蒂冈城国", "Vatican City State", "VA", "VAT", "336", "+379", "欧元", "Euro", "EUR"),
        _c("委内瑞拉", "Venezuela", "委内瑞拉玻利瓦尔共和国", "Bolivarian Republic of Venezuela", "VE", "VEN", "862", "+58", "玻利瓦尔", "Venezuelan Bolívar", "VES"),
        _c("越南", "Vietnam", "越南社会主义共和国", "Socialist Republic of Vietnam", "VN", "VNM", "704", "+84", "越南盾", "Vietnamese Đồng", "VND"),
        _c("美属维尔京群岛", "US Virgin Islands", "美属维尔京群岛", "Virgin Islands of the United States", "VI", "VIR", "850", "+1340", "美元", "US Dollar", "USD"),
        _c("瓦利斯和富图纳", "Wallis and Futuna", "瓦利斯和富图纳", "Wallis and Futuna", "WF", "WLF", "876", "+681", "太平洋法郎", "CFP Franc", "XPF"),
        _c("西撒哈拉", "Western Sahara", "西撒哈拉", "Western Sahara", "EH", "ESH", "732", "+212", "摩洛哥迪拉姆", "Moroccan Dirham", "MAD"),
        _c("也门", "Yemen", "也门共和国", "Republic of Yemen", "YE", "YEM", "887", "+967", "也门里亚尔", "Yemeni Rial", "YER"),
        _c("赞比亚", "Zambia", "赞比亚共和国", "Republic of Zambia", "ZM", "ZMB", "894", "+260", "赞比亚克瓦查", "Zambian Kwacha", "ZMW"),
        _c("津巴布韦", "Zimbabwe", "津巴布韦共和国", "Republic of Zimbabwe", "ZW", "ZWE", "716", "+263", "津巴布韦元", "Zimbabwean Dollar", "ZWL"),
    ])


def _c(name_zh, name_en, full_name_zh, full_name_en, iso_code_2, iso_code_3, numeric_code, phone_code, currency_name_zh, currency_name_en, currency_code):
    """辅助函数：构造国家数据字典"""
    return {
        "id": str(uuid4()),
        "name_zh": name_zh,
        "name_en": name_en,
        "full_name_zh": full_name_zh,
        "full_name_en": full_name_en,
        "iso_code_2": iso_code_2,
        "iso_code_3": iso_code_3,
        "numeric_code": numeric_code,
        "phone_code": phone_code,
        "currency_name_zh": currency_name_zh,
        "currency_name_en": currency_name_en,
        "currency_code": currency_code,
    }


def downgrade() -> None:
    op.drop_index('ix_countries_name_en', table_name='countries')
    op.drop_index('ix_countries_name_zh', table_name='countries')
    op.drop_index('ix_countries_iso_code_2', table_name='countries')
    op.drop_table('countries')
